name: Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        $Env:GOOS="linux"; $Env:GOARCH="amd64"; go build -o relay-linux ./cmd/relay
        $Env:GOOS="windows"; $Env:GOARCH="amd64"; go build -o relay-win.exe ./cmd/relay

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          relay-linux
          relay-win.exe
